//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vtdi_gate_logs
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gate_In_Out
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int VehicleType { get; set; }
        public string PlateNumber { get; set; }
        public int PurposeOfVisit { get; set; }
        public string Item_need_to_Declare { get; set; }
        public System.DateTime Date_time_in { get; set; }
        public string Date_time_out { get; set; }
        public int UserId { get; set; }
    
        public virtual Purpose_of_Visit Purpose_of_Visit { get; set; }
        public virtual User User { get; set; }
        public virtual Vehicle_types Vehicle_types { get; set; }
    }
}
