//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace vtdi_gate_logs
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Vtdi_school_gate_logdEntities : DbContext
    {
        public Vtdi_school_gate_logdEntities()
            : base("name=Vtdi_school_gate_logdEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Item_To_Declare> Item_To_Declare { get; set; }
        public virtual DbSet<Purpose_of_Visit> Purpose_of_Visit { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Vehicle_types> Vehicle_types { get; set; }
        public virtual DbSet<Gate_In_Out> Gate_In_Out { get; set; }
    }
}
